on:
  push:
    branches:
      - master

jobs:
  Github-Pages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/npm@v2.0.0
        with:
          args: install elm
      - uses: actions/npm@v2.0.0
        with:
          args: run build
      - uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: dist

# vim: set ts=2 sw=2 et:
